module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    PRODUCT_CATEGORY:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISHILIST_COLLECTION:'wishilist',
    BANNER_COLLECTION:'banner',
    COUPON_COLLECTION:'coupon'
}